/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { Html, useGLTF } from "@react-three/drei";
import Inventar from "../VirtualApp/Inventar/Inventar";

export function Datalogic(props) {
  const { nodes, materials } = useGLTF("./datalogic.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[0.075, 0.075, 0.06]} scale={50}>
          <mesh
            name="Screen"
            geometry={nodes.Screen.geometry}
            material={materials.Screen}
            position={[0, 0.083, 0]}
          >
                        <Html className="virtualApp"  scale={[0.01, 0.01, 0.01]} transform>
                            <div className="wrapper" onPointerDown={(e) => e.stopPropagation()}>
                                <Inventar/>
                            </div>
                      </Html>
            </mesh>
        </group>
        <mesh
          name="Connector"
          geometry={nodes.Connector.geometry}
          material={materials.GoldConnector}
          position={[-0.264, -3.127, -0.648]}
        />
        <mesh
          name="Connector001"
          geometry={nodes.Connector001.geometry}
          material={materials.GoldConnector}
          position={[-0.204, -3.127, -0.74]}
        />
        <mesh
          name="Touches_Num_C"
          geometry={nodes.Touches_Num_C.geometry}
          material={materials.touche}
          position={[0.075, -0.367, -0.026]}
          scale={50}
        />
        <mesh
          name="Touche_TRIGGER_Central"
          geometry={nodes.Touche_TRIGGER_Central.geometry}
          material={materials.touche}
          position={[0.075, 0.909, -0.026]}
          scale={50}
        />
        <mesh
          name="Touches_Num_D"
          geometry={nodes.Touches_Num_D.geometry}
          material={materials.touche}
          position={[0.716, -0.367, -0.026]}
          scale={50}
        />
        <mesh
          name="Touche_ENT_D"
          geometry={nodes.Touche_ENT_D.geometry}
          material={materials.touche}
          position={[0.947, 0.898, -0.026]}
          scale={50}
        />
        <mesh
          name="Touche_ENT_G"
          geometry={nodes.Touche_ENT_G.geometry}
          material={materials.touche}
          position={[-0.718, 0.898, -0.026]}
          scale={50}
        />
        <mesh
          name="Touches_Num_G"
          geometry={nodes.Touches_Num_G.geometry}
          material={materials.touche}
          position={[-0.556, -0.367, -0.026]}
          scale={50}
        />
        <mesh
          name="Touche_F"
          geometry={nodes.Touche_F.geometry}
          material={materials.touche}
          position={[-0.767, 0.093, -0.026]}
          scale={[24.756, 26.486, 50]}
        />
        <mesh
          name="Touche_Directionnelles"
          geometry={nodes.Touche_Directionnelles.geometry}
          material={materials.touche}
          position={[-0.716, 0.433, -0.026]}
          scale={[34.548, 26.486, 50]}
        />
        <mesh
          name="Touches_null"
          geometry={nodes.Touches_null.geometry}
          material={materials.touche}
          position={[0.075, -2.106, -0.026]}
          scale={[42.08, 42.08, 50]}
        />
        <mesh
          name="Touches_BKSP"
          geometry={nodes.Touches_BKSP.geometry}
          material={materials.touche}
          position={[0.547, -2.131, -0.026]}
          scale={[22.033, 33.943, 50]}
        />
        <mesh
          name="Touches_Dot"
          geometry={nodes.Touches_Dot.geometry}
          material={materials.touche}
          position={[-0.412, -2.131, -0.026]}
          scale={[22.033, 33.943, 50]}
        />
        <mesh
          name="Touches_Num_TAB"
          geometry={nodes.Touches_Num_TAB.geometry}
          material={materials.touche}
          position={[0.885, -2.131, -0.026]}
          scale={[22.033, 33.943, 50]}
        />
        <mesh
          name="Touches_Esc"
          geometry={nodes.Touches_Esc.geometry}
          material={materials.touche}
          position={[-0.771, -2.131, -0.026]}
          scale={[22.033, 33.943, 50]}
        />
        <mesh
          name="Touches_BLUE"
          geometry={nodes.Touches_BLUE.geometry}
          material={materials.touche}
          position={[0.378, -2.507, -0.026]}
          scale={[29.539, 26.999, 50]}
        />
        <mesh
          name="Touches_YEL"
          geometry={nodes.Touches_YEL.geometry}
          material={materials.touche}
          position={[-0.235, -2.507, -0.026]}
          scale={[29.539, 26.999, 50]}
        />
        <mesh
          name="Touche_TRIGGER_Central001"
          geometry={nodes.Touche_TRIGGER_Central001.geometry}
          material={materials.touche}
          position={[1.883, 3.238, -0.564]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          name="Touche_TRIGGER_Central002"
          geometry={nodes.Touche_TRIGGER_Central002.geometry}
          material={materials.touche}
          position={[-1.745, 3.238, -0.564]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        />
        <mesh
          name="Touche_TRIGGER_Central003"
          geometry={nodes.Touche_TRIGGER_Central003.geometry}
          material={materials.touche}
          position={[1.883, 5.108, -0.564]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          name="Touche_TRIGGER_Central004"
          geometry={nodes.Touche_TRIGGER_Central004.geometry}
          material={materials.touche}
          position={[-1.745, 5.108, -0.564]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        />
        <group name="coque" position={[0.075, 2.178, 0.06]}>
          <mesh
            name="Plane005"
            geometry={nodes.Plane005.geometry}
            material={materials.blackRought}
          />
          <mesh
            name="Plane005_1"
            geometry={nodes.Plane005_1.geometry}
            material={materials.blackGlossy}
          />
          <mesh
            name="Plane005_2"
            geometry={nodes.Plane005_2.geometry}
            material={materials.ScreenContour}
          />
        </group>
        <mesh
          name="Bute"
          geometry={nodes.Bute.geometry}
          material={materials.blackGlossy}
          position={[0.075, 1.229, 0.063]}
          scale={50}
        />
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials.blackGlossy}
          position={[0.075, -1.799, 0.06]}
        />
        <mesh
          name="coque001"
          geometry={nodes.coque001.geometry}
          material={materials.glass}
          position={[0.075, 2.178, 0.06]}
        />
        <mesh
          name="coque002"
          geometry={nodes.coque002.geometry}
          material={materials["blackRought.001"]}
          position={[0.075, 2.178, 0.06]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./datalogic.glb");